### ISSUE TITLE
Compressor algorithm

### ISSUE THREAD

**Issue by heapx** [AidaDSP/AidaDSP#1]
Hi, thanks for a great library. I have a question regarding the "CompressorRMS" algorithm, as far as I understand this for the "Post Gain" block in Sigma Studio, while I'm trying to use the "Standard RMS" block
![image](https://user-images.githubusercontent.com/451729/28120231-b3b0cfb4-6717-11e7-973a-143ce95be8e8.png)

I can't find much information about how to generate the parameters for this block, so I was wondering whether you had any pointers on that or what changes I would have to make to the "CompressorRMS" function to generate those.

**Comment by MaxPayne86** [comment]
Hi, unfortunately I didn't find any specific documentation on the block behaviour so I reverse-engineered the output from Sigma Studio in the output capture window. I did some tests in matlab searching for a simple algorithm that permits me to obtain a dynamic processor curve with the parameters in the compressor_t struct defined [here](https://github.com/AidaDSP/AidaDSP/blob/master/Software/Libraries/Arduino/Aida/AidaDSP.h). At first you can try to comment #define COMPRESSORWITHPOSTGAIN and recompile. This should give you the compressor functionality using your block. In a second time, you should really think on how to generate a compressor/expander curve with variable knee as it's done by the interface (but how it's done, we don't know). Try to ask also on engineerzone and let me know!
