### ISSUE TITLE
Can I make this work for the latest boards ?

### ISSUE THREAD

**Issue by lalalandaudio** [AidaDSP/AidaDSP#10]
Has this been abandoned or can I make this work with a 1466 eval board ?

**Comment by MaxPayne86** [comment]
Hi, this project is not abandoned, this library currently supports 170x and 144x Sigma DSP families. There are many part numbers in Sigma DSP product line and supporting all of them would be super good, but unfortunately those boards are not free and my time is limited. Feel free to send me a pull request! ;)
