### ISSUE TITLE
Write block with original Wire library

### ISSUE THREAD

**Issue by MCUdude** [AidaDSP/AidaDSP#6]
Hi!
I'm working on a new SigmaDSP library that's based on the incredible work you have put into this library. The library I'm working on will be open source and published when ready.

I want the library to support the Arduino platform, and architecture independent. Personally I'll use my new library with ESP8266, but I have an issue I'd like to discuss.

You have provided a separate i2c library (WireMod), but I want to use the original Wire library that everyone uses. Is it possible to re-create the writeblock functionality using the stock wire library. I'm sure lots of users would prefer not to install another library for i2c communication. 

Thanks!

**Comment by MCUdude** [comment]
After a bit more digging it seems like the modification was made in order to point to the array to send directly rather than the i2c TX buffer, since it's only 32 bytes long.

**Comment by MCUdude** [comment]
I solved it by writing four or five bytes at the time, depending on where in the memory the content should be stored. Works like a charm!

**Comment by MaxPayne86** [comment]
Hi, using your approach you're lowering the performance of the library comparing to my implementation: at least inform your users of this issue. Honestly I don't see so much troubles in copying new Wire libraries it's well documented [here](https://github.com/AidaDSP/AidaDSP/wiki/Install-libraries-and-dependencies)
