### ISSUE TITLE
AidaDSP

### ISSUE THREAD

**Issue by MohammedZwayen** [AidaDSP/AidaDSP#8]
I really appreciate your work 
i have one question :
-what is the purpose from adding writeBlock function since i am facing problems in porting your work to esp32

**Comment by MaxPayne86** [comment]
The main reason of tweaking the low level i2c libraries is to add the function to write on i2c from a "stream" or a pointer to an area in memory. When you have to write 2k+ bytes to a target like in case of a Sigma DSP, if you stop and restart after every 4-5 bytes you're slowing down the programming procedure, so my workaround is more elegant but difficult to maintain and port. This is definitely a feature that should be added and maintained inside Arduino core, I'm planning to submit a patch...regarding your "porting", I'm working in these days on a version of the library doesn't need writeBlock for teensy (and other platforms) compatibility. It's still under debug (doesn't work). Have a look into this branch: bug-fix/wiremod-dependency
