### ISSUE TITLE
Wrong SR definition

### ISSUE THREAD

**Issue by mr-miky** [AidaDSP/AidaDSP#9]
Referring to page 82 of the datasheet, it is necessary to wait at least 1 sampling period so SR, which in reality should be SP, should result

#define SP (uint32_t) (1000000.0 / FS)

#define SR (uint32_t) 1 / FS
it is always 0 due to the casting and in any case they are seconds and not microseconds.

Ciao Max....

**Comment by MaxPayne86** [comment]
Fixed in 23ac3f4242e64500f26e0319c8dc4d058cb51772 thank you @mr-miky!
